apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-value-store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: key-value-store-app
  template:
    metadata:
      labels:
        app: key-value-store-app
    spec:
      containers:
      - name: key-value-store
        image: hiprateekyadav/key-value-store:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data-volume
          mountPath: /code/database
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
