apiVersion: v1
kind: Service
metadata:
  name: key-value-store-app-service
spec:
  selector:
    app: key-value-store-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000  
      nodePort: 31787
  type: NodePort
